services:
  - type: web
    name: ai-based-skill-evaluator
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: DATABASE_URL
        sync: false
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        sync: false
      - key: INNGEST_EVENT_KEY
        sync: false
      - key: INNGEST_SIGNING_KEY
        sync: false
